Add tests for operators
macabeus/rust-neander pull request #2
Opened 2019-01-16 01:21 UTC by otaviopace

This Pull Request adds tests for the `state/operators` instances.

To verify that the tests pass just run `cargo test` on your terminal :slightly_smiling_face: .

2019-01-16 05:19 UTC, macabeus requested changes

2019-01-16 05:19 UTC, macabeus commented on src/state/tests.rs
> +fn jn_when_accumulator_is_one() {
Creio que seja melhor mudar o nome dessa função para `jn_when_accumulator_is_negative`

2019-01-16 05:19 UTC, macabeus commented on src/state/tests.rs
> +fn jn_when_accumulator_is_not_one() {
Creio que seja melhor mudar o nome dessa função para `jn_when_accumulator_is_positive`

2019-01-16 05:19 UTC, macabeus commented on src/state/tests.rs
> +    assert_eq!(new_state.ac, state.ac);
Esse teste acaba testando muito pouco, pois o input é `0`, e o acumulador já é `0`.
Seria melhor fazer com que o input fosse um valor diferente, criando o `State` com algo assim `State::new([0; 255], [1; 255])` e então testar.

2019-01-17 03:28 UTC, evaporei commented on src/state/tests.rs
> +fn jn_when_accumulator_is_one() {
Ajustado!

2019-01-17 03:28 UTC, evaporei commented on src/state/tests.rs
> +fn jn_when_accumulator_is_not_one() {
Ajustado!

2019-01-17 03:28 UTC, evaporei commented on src/state/tests.rs
> +    assert_eq!(new_state.ac, state.ac);
Eu fiz a modificação no teste, pode dar uma olhada para ver se agora está melhor?

2019-01-17 03:43 UTC, macabeus approved these changes
:100:

2019-01-17 03:44 UTC, merged

2019-01-17 03:51 UTC, otaviopace commented
Uhuuuullll!!!! :tada: :confetti_ball: